apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
spec:
  rules:
    - host: music.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 80
